export const BASE_PRICES = {
  "aop kids tee": 28,
  "sticker sheet": 8,
  sticker: 5,
  tee: 16,
  "kids tee": 21,
  "aop tee": 31,
  "sleeveless aop crop tee": 21,
  "aop crop tee": 25,
  "crop tee": 21,
  tank: 22,
  "aop tank": 32,
  "aop hoodie": 46,
  "premium hoodie": 29,
  hoodie: 26,
  "aop sweatshirt": 42,
  sweatshirt: 27,
  mug: 15,
  "iphone case": 20,
  "samsung case": 20,
  apron: 28,
  headband: 10,
  backpack: 38,
  drawstring: 20,
  "aop tote": 28,
  tote: 22,
  "fanny pack": 35,
  "laptop case": 30,
  "crop sleeveless tee": 28,
  tumbler: "28",
  scrunchie: 15,
  bandana: 13,
  "gym bag": 60
}
