export const getProductType = (name: string) => {
  if (name.includes("aop kids tee")) return "aop kids tee"
  if (name.includes("kids tee")) return "kids tee"
  if (name.includes("crop tee")) return "crop tee"
  if (name.includes("sticker sheet")) return "sticker sheet"
  if (name.includes("sticker")) return "sticker"
  if (name.includes("tee")) return "tee"
  if (name.includes("apron")) return "apron"
  if (name.includes("tank")) return "tank"
  if (name.includes("hoodie")) return "hoodie"
  if (name.includes("sweatshirt")) return "sweatshirt"
  if (name.includes("mug")) return "mug"
  if (name.includes("leggings")) return "leggings"
  if (name.includes("samsung case")) return "samsung case"
  if (name.includes("iphone case")) return "iphone case"
  if (name.includes("tote")) return "tote"
  if (name.includes("drawstring")) return "drawstring"
  if (name.includes("crop sleeveless tee")) return "crop sleeveless tee"
  if (name.includes("laptop case")) return "laptop case"
  if (name.includes("backpack")) return "backpack"
  if (name.includes("headband")) return "headband"
  if (name.includes("fanny pack")) return "fanny pack"
  if (name.includes("tumbler")) return "tumbler"
  if (name.includes("scrunchie")) return "scrunchie"
  if (name.includes("bandana")) return "bandana"
  if (name.includes("gym bag")) return "gym bag"

  return "tee"
}
